---
vector_version: "0.46.0"
vector_arch: "x86_64-unknown-linux-gnu"
vector_download_url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-{{ vector_arch }}.tar.gz"

vector_install_dir: /opt/vector
vector_bin_path: /usr/local/bin/vector
vector_config_dir: /etc/vector
vector_data_dir: /var/lib/vector
vector_config_file: "{{ vector_config_dir }}/vector.yaml"

vector_source: journald
vector_sink_type: console
